In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

import sqlite3
import pandas as pd

DB_PATH = PROJECT_ROOT / "data" / "nifty100.db"

conn = sqlite3.connect(DB_PATH)

In [2]:
query = """
SELECT
    company_id,
    year,
    return_on_equity_pct,
    debt_to_equity
FROM financial_ratios
WHERE
    return_on_equity_pct > 15
AND
    debt_to_equity < 1
ORDER BY
    return_on_equity_pct DESC
"""

screener = pd.read_sql(query, conn)

screener

     company_id    year  return_on_equity_pct  debt_to_equity
0        INDIGO  2015.0           4939.393939        0.151515
1           BEL  2024.0           4744.047619        0.511905
2           BEL  2023.0           3981.333333        0.520000
3           BEL  2019.0           3851.020408        0.959184
4           HAL  2024.0           3816.582915        0.618090
..          ...     ...                   ...             ...
402        GAIL  2013.0             15.166354        0.572064
403  BAJAJHLDNG  2015.0             15.149705        0.000000
404   SUNPHARMA  2024.0             15.094162        0.051424
405     HAVELLS  2017.0             15.079365        0.063492
406        ONGC  2017.0             15.005710        0.411701

[407 rows x 4 columns]

In [3]:
OUTPUT = PROJECT_ROOT / "output"

screener.to_csv(
    OUTPUT / "quality_screener.csv",
    index=False
)

print("quality_screener.csv created successfully!")

quality_screener.csv created successfully!

In [4]:
screener.describe()

              year  return_on_equity_pct  debt_to_equity
count   407.000000            407.000000      407.000000
mean   2018.270270            166.229891        0.161927
std       3.514316            645.539479        0.245423
min    2011.000000             15.005710        0.000000
25%    2015.000000             20.030387        0.005870
50%    2018.000000             24.863152        0.054215
75%    2021.000000             35.563106        0.153644
max    2024.000000           4939.393939        0.988655